### ISSUE TITLE
Is it possible to avoid code nesting and enable the zoomable effect on any widget in the form of modifier?

### ISSUE THREAD

**Issue by minoism** [Tlaster/Zoomable#1]
Such as 
```kotlin
val state = rememberZoomableState(
    minScale = 2f
)
Text(modifier = Modifier.zoomable())
Image(modifier = Modifier.zoomable())
...
```

**Comment by Tlaster** [comment]
Currently, we "cache" the child's size as state, calculate the bounds with it and constraints from BoxWithConstraints, it is possible but might not be the best practice from the [API guideline](https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-api-guidelines.md)

**Comment by minoism** [comment]
Oh well, I haven't read the api guide specification yet, I think I will spend some time reading it. The reason for me asking this question is that there was a zoomable modifier before the compose-beta, but it was deleted for some reasons later? But it’s okay. I found this library now, so I have some questions about it.

**Comment by minoism** [comment]
Now this issue can be closed, thanks for your answer.
