### ISSUE TITLE
Can not be used as a list item inside LazyColumn

### ISSUE THREAD

**Issue by V9vek** [Tlaster/Zoomable#13]
I tried to use it as an item inside `items{}` while using `LazyColumn`, but the image is not shown at all.
Is this because it uses `BoxWithConstraints` with `maxHeight` and `maxWidth`?

**Comment by TepesLucian** [comment]
Not sure if this is the usecase you are looking for : https://github.com/V9vek/PinchToZoom

**Comment by V9vek** [comment]
Thanks for questioning the query.
Actually, yeah I implemented this ``` PinchToZoom ``` thing later, by having some help
This is the link to the my repo only, no? 😅

**Comment by TepesLucian** [comment]
Shoot, my bad. 🤣
