### ISSUE TITLE
Canvas in Zoomable

### ISSUE THREAD

**Issue by wakaztahir** [Tlaster/Zoomable#4]
I am using a canvas composable inside surface composable with fillMaxSize , I want the canvas to zoom inside its layout but when I try to zoom , it expands over other composables

I want it to fit screen so I didn't define a fixed width and height !

Here's a gif showing the problem : 
https://ibb.co/2WsGDTB

My Code (I've eliminated some code that was mostly drawing specific !) : 

```
    Box(modifier = Modifier.wrapContentSize()) {
        Surface(modifier = Modifier.fillMaxSize()) {
            Canvas(
                modifier = Modifier
                    .fillMaxSize()
            ) 
            }
        }
```

I don't know if the problem is due to zoomable , I don't know how to fix it !
But considering that it happens everytime I zoom , I think this is the best place to look for help !
Thanks in advance !

**Comment by wakaztahir** [comment]
updated gif !

**Comment by Tlaster** [comment]
I don't think it's a zoomable bug, this just that you're not familiar with the basic compose API usage.
Like the old android view base's FrameLayout, you should declare the zoomable with the right position, or define a z-index in your toolbar (which is not recommended).
