### ISSUE TITLE
Cannot drag fully zoomed composable

### ISSUE THREAD

**Issue by janbina** [Tlaster/Zoomable#9]
Drag gesture is enabled only when `state.zooming == true` and `state.zooming = scale > minScale && scale < maxScale`. This means that when some finite number is used for `maxScale`, fully zoomed composable cannot be dragged. Is this intentional? It feels more like a bug, `state.zooming = scale > minScale` will be more appropriate, I guess.

**Comment by Tlaster** [comment]
Thanks, it is a bug, I didn't notice that
